// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNLV-OeEGO9LhxPh0qlJ6xaQa0ILUIkM',
    appId: '1:866718998655:web:a2abc8da8ac6eb9b225f4a',
    messagingSenderId: '866718998655',
    projectId: 'evenly-c16-mon',
    authDomain: 'evenly-c16-mon.firebaseapp.com',
    storageBucket: 'evenly-c16-mon.firebasestorage.app',
    measurementId: 'G-9C7H9RDDQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnknMVY79cbCImCk1_j_WvDLkFIBXBGI',
    appId: '1:866718998655:android:d245d5f8a9229234225f4a',
    messagingSenderId: '866718998655',
    projectId: 'evenly-c16-mon',
    storageBucket: 'evenly-c16-mon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCes5K4uw4jXZXw2Zv40tKYO8nJzx56OK4',
    appId: '1:866718998655:ios:57c13df917662182225f4a',
    messagingSenderId: '866718998655',
    projectId: 'evenly-c16-mon',
    storageBucket: 'evenly-c16-mon.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16Mon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCes5K4uw4jXZXw2Zv40tKYO8nJzx56OK4',
    appId: '1:866718998655:ios:57c13df917662182225f4a',
    messagingSenderId: '866718998655',
    projectId: 'evenly-c16-mon',
    storageBucket: 'evenly-c16-mon.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16Mon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcNLV-OeEGO9LhxPh0qlJ6xaQa0ILUIkM',
    appId: '1:866718998655:web:2268849753c13dfd225f4a',
    messagingSenderId: '866718998655',
    projectId: 'evenly-c16-mon',
    authDomain: 'evenly-c16-mon.firebaseapp.com',
    storageBucket: 'evenly-c16-mon.firebasestorage.app',
    measurementId: 'G-4GBF6FZMEQ',
  );
}
