// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UWc2pOtNM0eGx6yyklyPDOumT13UxtY',
    appId: '1:49818994677:web:e9bd17bb46f71fe85982bc',
    messagingSenderId: '49818994677',
    projectId: 'evently-c18-7a7a3',
    authDomain: 'evently-c18-7a7a3.firebaseapp.com',
    storageBucket: 'evently-c18-7a7a3.firebasestorage.app',
    measurementId: 'G-XBTPTJ8L95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnR9SXwNm-xThd050cqCPIaM3pyW1R5Bk',
    appId: '1:49818994677:android:13a03eb92b627e7b5982bc',
    messagingSenderId: '49818994677',
    projectId: 'evently-c18-7a7a3',
    storageBucket: 'evently-c18-7a7a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgwkyjKTAPJlYAOqv5PXnPZVyfwBhZHAM',
    appId: '1:49818994677:ios:1c1c8eb555cdbfc35982bc',
    messagingSenderId: '49818994677',
    projectId: 'evently-c18-7a7a3',
    storageBucket: 'evently-c18-7a7a3.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16Mon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgwkyjKTAPJlYAOqv5PXnPZVyfwBhZHAM',
    appId: '1:49818994677:ios:1c1c8eb555cdbfc35982bc',
    messagingSenderId: '49818994677',
    projectId: 'evently-c18-7a7a3',
    storageBucket: 'evently-c18-7a7a3.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16Mon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5UWc2pOtNM0eGx6yyklyPDOumT13UxtY',
    appId: '1:49818994677:web:90f4eaef959c36485982bc',
    messagingSenderId: '49818994677',
    projectId: 'evently-c18-7a7a3',
    authDomain: 'evently-c18-7a7a3.firebaseapp.com',
    storageBucket: 'evently-c18-7a7a3.firebasestorage.app',
    measurementId: 'G-HN4L5JMLPQ',
  );

}